name: Build and push wapi03 Docker image to Azure Container Registry 

on:
  workflow_dispatch
 
  # Whenever required change the Major release number environment variable below
env:
  MAJOR: '1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
     
      - name: Output Version Number
        run: echo $MAJOR.${{ github.run_number }}.${{ github.run_attempt }}
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t k8stestacreastus2.azurecr.io/wapi03:$MAJOR.${{ github.run_number }}.${{ github.run_attempt }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: k8stestacreastus2.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image to Azure Container Registry
        run: docker push k8stestacreastus2.azurecr.io/wapi03:$MAJOR.${{ github.run_number }}.${{ github.run_attempt }}

    