name: Build and push wapi03 Docker image to Azure Container Registry 

on:
  workflow_dispatch
 
env:
  MAJOR: '1'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Ubuntu Bash
        run: echo "Hello, world!"
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - name: Output Version Number
        run: echo $MAJOR.${{ github.run_number }}.${{ github.run_attempt }}
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Build Docker image
    #   run: docker build . -t k8stestacreastus2.azurecr.io/wapi03:${{ secrets.MAJOR }}.${{ secrets.MINOR }}

    # - name: Log in to Azure Container Registry
    #   uses: azure/docker-login@v1
    #   with:
    #     login-server: k8stestacreastus2.azurecr.io
    #     username: ${{ secrets.REGISTRY_USERNAME }}
    #     password: ${{ secrets.REGISTRY_PASSWORD }}

    # - name: Push Docker image to Azure Container Registry
    #   run: docker push k8stestacreastus2.azurecr.io/wapi03:${{ secrets.MAJOR }}.${{ secrets.MINOR }}

    # - name: Update Minor version
    #   uses: hmanzur/actions-set-secret@v2.0.0
    #   with:
    #     name: 'MINOR'
    #     value: $((${{ secrets.MINOR }}+1))
    #     repository: ACRWork/wapi03
    #     token: ${{ secrets.GITHUB_TOKEN }}
